version: "1.0"

services:
  address:
    image: address-management-system
    build: .
    ports:
      - '3000:3000'
    networks:
      - address-api

    stdin_open: true
    tty: true

networks:
  address-api:

